### ISSUE TITLE
Automatically add labels to github pull requests

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client#122]
Related to: https://github.com/g3w-suite/g3w-client/pull/120, it may be worth adding labels automatically in order to generate releases notes in a simpler and faster way:

- https://github.com/marketplace/actions/labeler
- https://github.com/qgis/QGIS/commit/ef14f6a78baff923d73332f433673c7d66a8a620
- [Add useful labels to your Pull Requests with Github Actions](https://blog.dipien.com/add-useful-labels-to-your-pull-requests-with-github-actions-33c3f8ca59b2)

Here is a fairly comprehensive list of some the labels that could be used: https://github.com/qgis/QGIS/labels

---

Basic example:

```yml
# .github/labeler.yml

# Add 'label1' to any changes within 'example' folder or any subfolders
label1:
- example/**/*

# Add 'label2' to any file changes within 'example2' folder
label2: example2/*

# Add 'repo' label to any root file changes
repo:
- '*'

# Add '@domain/core' label to any change within the 'core' package
@domain/core:
- package/core/*
- package/core/**/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
- src/**/*.spec.js

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*', '!src/docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['src/**/*.js']
  all: ['!src/main.js']
```
